service: backend-template

plugins:
  - serverless-python-requirements
  - serverless-prune-plugin
custom:
  pythonRequirements:
    dockerizePip: true
    noDeploy:
      - boto3
      - botocore
      - pylint
      - autopep8
      - pytest
  prune:
    automatic: true
    number: 3
  stage: ${self:provider.stage}
  project: backend-template
  prefix: ${self:custom.project}-${self:custom.stage}
  sns-dead-arn: arn:aws:sns:${aws:region}:${aws:accountId}:${self:custom.prefix}-dead
  sqs-dead-arn: arn:aws:sqs:${aws:region}:${aws:accountId}:${self:custom.prefix}-dead

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'prod'}
  versionFunctions: false
  environment:
    REGION: eu-central-1
    PREFIX: ${self:custom.prefix}
    MONGODB_URL: ${env:MONGODB_URL}
    MONGODB_DATABASE: ${env:MONGODB_DATABASE}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource:
        - arn:aws:ssm:${aws:region}:${aws:accountId}:parameter/${self:custom.prefix}_*
    - Effect: Allow
      Action:
        - lambda:invokeFunction
      Resource:
        - arn:aws:lambda:${aws:region}:*:function:${self:custom.prefix}*
    - Effect: Allow
      Action:
        - sns:Publish
      Resource:
        - arn:aws:sns:${aws:region}:${aws:accountId}:${self:custom.prefix}-*
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:GetQueueUrl
      Resource:
        - arn:aws:sqs:${aws:region}:${aws:accountId}:${self:custom.prefix}-*
    - Effect: Allow
      Action:
        - events:PutEvents
      Resource: "*"
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:ListObjectsV2
      Resource:
        - arn:aws:s3:::${self:custom.prefix}-*/*

package:
  include:
    - src/**
  exclude:
    - .idea/**
    - .serverless/**
    - .vscode/**
    - venv/**
    - node_modules/**
    - __pycache__/**
    - ./*.iml

functions:

  ping:
    handler: src/handler.ping
    onError: ${self:custom.sns-dead-arn}
    memorySize: 128
    timeout: 30
    events:
      - httpApi:
          method: 'GET'
          path: /v1/ping

resources:
  Resources:

    # dead letters

    LambdasDeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.prefix}-dead
        MessageRetentionPeriod: 1209600

    LambdasDeadSNS:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:custom.prefix}-dead
        Subscription:
          - Protocol: sqs
            Endpoint: ${self:custom.sqs-dead-arn}

    DeadLetterQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal: '*'
              Action: SQS:SendMessage
              Resource: ${self:custom.sqs-dead-arn}
              Condition:
                ArnEquals:
                  'aws:SourceArn': ${self:custom.sns-dead-arn}
        Queues:
          - Ref: LambdasDeadLetterQueue