name: Deploy Prod
on:
  push:
#    tags: # Deploy tag (e.g. v1.0) to production
#      - 'v**'
    branches:
      - master
jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: install serverless framework
        run: npm install -g serverless
      - name: install npm
        run: npm install
      - name: install serverless-pseudo-parameters
        run: sls plugin install -n serverless-pseudo-parameters
      - name: install serverless-python-requirements
        run: sls plugin install -n serverless-python-requirements
      - name: setup aws auth
        run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: serverless deploy
        run: sls deploy --force --region us-east-1